import type { ReadingPassage } from "@/lib/types";

export const readingPassages: ReadingPassage[] = [
  // ── A1 ──────────────────────────────────────────────────────────────
  {
    id: "reading-a1-family",
    title: "Meine Familie",
    level: "A1",
    topic: "Family",
    text: `Ich heiße Anna. Ich habe eine kleine Familie. Mein Vater heißt Klaus und er ist fünfzig Jahre alt. Meine Mutter heißt Maria und sie ist siebenundvierzig Jahre alt. Ich habe einen Bruder. Er heißt Max und er ist zwölf Jahre alt. Wir wohnen in Berlin. Unser Haus ist nicht groß, aber es ist sehr schön. Wir haben auch einen Hund. Er heißt Bello und er ist sehr lieb.`,
    textEn: `My name is Anna. I have a small family. My father is called Klaus and he is fifty years old. My mother is called Maria and she is forty-seven years old. I have one brother. His name is Max and he is twelve years old. We live in Berlin. Our house is not big, but it is very nice. We also have a dog. His name is Bello and he is very sweet.`,
    tooltips: {
      Familie: "family",
      Vater: "father",
      Mutter: "mother",
      Bruder: "brother",
      wohnen: "to live/reside",
      Hund: "dog",
      lieb: "sweet, dear",
    },
    exercises: [
      {
        id: "ra1f-mc1",
        type: "multipleChoice",
        question: "Wie heißt Annas Vater?",
        options: ["Max", "Klaus", "Bello", "Hans"],
        correctIndex: 1,
        explanation: "Der Text sagt: 'Mein Vater heißt Klaus'.",
      },
      {
        id: "ra1f-mc2",
        type: "multipleChoice",
        question: "Wo wohnt Annas Familie?",
        options: ["München", "Hamburg", "Berlin", "Wien"],
        correctIndex: 2,
        explanation: "Der Text sagt: 'Wir wohnen in Berlin'.",
      },
      {
        id: "ra1f-fb1",
        type: "fillBlank",
        prompt: "Annas Bruder heißt ___ und ist zwölf Jahre alt.",
        answer: "Max",
        explanation: "Der Text nennt den Bruder 'Max'.",
      },
      {
        id: "ra1f-fb2",
        type: "fillBlank",
        prompt: "Der Hund der Familie heißt ___.",
        answer: "Bello",
        explanation: "Der Text sagt: 'Er heißt Bello'.",
      },
    ],
  },
  {
    id: "reading-a1-school",
    title: "Ein Tag in der Schule",
    level: "A1",
    topic: "Daily life",
    text: `Ich gehe jeden Tag in die Schule. Die Schule beginnt um acht Uhr. Zuerst haben wir Deutsch. Der Lehrer heißt Herr Braun. Er ist sehr nett. Nach Deutsch haben wir Mathematik. Mathematik ist schwer, aber interessant. Um zwölf Uhr essen wir in der Kantine. Das Essen ist gut. Am Nachmittag habe ich Sport. Sport macht mir Spaß. Um drei Uhr fahre ich mit dem Bus nach Hause.`,
    textEn: `I go to school every day. School starts at eight o'clock. First we have German. The teacher is called Mr Braun. He is very nice. After German we have Maths. Maths is hard but interesting. At twelve o'clock we eat in the canteen. The food is good. In the afternoon I have Sport. I enjoy sport. At three o'clock I take the bus home.`,
    tooltips: {
      Schule: "school",
      Lehrer: "teacher",
      Mathematik: "mathematics",
      schwer: "hard, difficult",
      Kantine: "canteen",
      Nachmittag: "afternoon",
      "macht mir Spaß": "I enjoy / it's fun for me",
    },
    exercises: [
      {
        id: "ra1s-mc1",
        type: "multipleChoice",
        question: "Um wie viel Uhr beginnt die Schule?",
        options: ["Sieben Uhr", "Acht Uhr", "Neun Uhr", "Zehn Uhr"],
        correctIndex: 1,
        explanation: "'Die Schule beginnt um acht Uhr.'",
      },
      {
        id: "ra1s-mc2",
        type: "multipleChoice",
        question: "Was macht das Kind um drei Uhr?",
        options: ["Isst in der Kantine", "Spielt Sport", "Fährt nach Hause", "Hat Mathematik"],
        correctIndex: 2,
        explanation: "'Um drei Uhr fahre ich mit dem Bus nach Hause.'",
      },
      {
        id: "ra1s-fb1",
        type: "fillBlank",
        prompt: "Der Lehrer heißt Herr ___.",
        answer: "Braun",
        explanation: "Der Text nennt den Lehrer 'Herr Braun'.",
      },
      {
        id: "ra1s-fb2",
        type: "fillBlank",
        prompt: "Um zwölf Uhr essen die Schüler in der ___.",
        answer: "Kantine",
        explanation: "'Um zwölf Uhr essen wir in der Kantine.'",
      },
    ],
  },

  // ── A2 ──────────────────────────────────────────────────────────────
  {
    id: "reading-a2-supermarket",
    title: "Im Supermarkt",
    level: "A2",
    topic: "Shopping",
    text: `Jeden Samstag gehe ich mit meiner Mutter in den Supermarkt. Wir kaufen Lebensmittel für die ganze Woche. Heute brauchen wir Brot, Milch, Käse, Äpfel und Nudeln. Im Supermarkt gibt es viele Menschen. Zuerst gehen wir in die Obst- und Gemüseabteilung. Dann holen wir Milchprodukte aus dem Kühlregal. An der Kasse warten wir kurz, weil viele Leute vor uns stehen. Wir bezahlen fünfundzwanzig Euro und fahren nach Hause.`,
    textEn: `Every Saturday I go to the supermarket with my mother. We buy groceries for the whole week. Today we need bread, milk, cheese, apples and pasta. The supermarket is busy. First we go to the fruit and vegetable section. Then we get dairy products from the fridge. At the checkout we wait briefly because many people are ahead of us. We pay twenty-five euros and drive home.`,
    tooltips: {
      Lebensmittel: "groceries, food items",
      Obstabteilung: "fruit section",
      Gemüseabteilung: "vegetable section",
      Kühlregal: "refrigerated shelf",
      Kasse: "checkout, till",
      bezahlen: "to pay",
    },
    exercises: [
      {
        id: "ra2s-mc1",
        type: "multipleChoice",
        question: "Wann geht die Person in den Supermarkt?",
        options: ["Montags", "Freitags", "Samstags", "Sonntags"],
        correctIndex: 2,
        explanation: "'Jeden Samstag gehe ich … in den Supermarkt.'",
      },
      {
        id: "ra2s-mc2",
        type: "multipleChoice",
        question: "Wie viel bezahlen sie an der Kasse?",
        options: ["Fünfzehn Euro", "Zwanzig Euro", "Fünfundzwanzig Euro", "Dreißig Euro"],
        correctIndex: 2,
        explanation: "'Wir bezahlen fünfundzwanzig Euro.'",
      },
      {
        id: "ra2s-fb1",
        type: "fillBlank",
        prompt: "Zuerst gehen sie in die Obst- und ___abteilung.",
        answer: "Gemüse",
        explanation: "Der erste Abschnitt im Supermarkt ist die Obst- und Gemüseabteilung.",
      },
      {
        id: "ra2s-fb2",
        type: "fillBlank",
        prompt: "Milchprodukte holen sie aus dem ___.",
        answer: "Kühlregal",
        explanation: "'Dann holen wir Milchprodukte aus dem Kühlregal.'",
      },
    ],
  },
  {
    id: "reading-a2-weather",
    title: "Das Wetter in Deutschland",
    level: "A2",
    topic: "Weather",
    text: `Das Wetter in Deutschland ist sehr unterschiedlich. Im Winter ist es kalt und es schneit oft. Die Temperaturen können bis zu minus zehn Grad fallen. Im Frühling wird es wärmer und die Blumen blühen. Im Sommer ist es meistens warm und sonnig, aber es gibt auch Gewitter. Im Herbst fallen die Blätter von den Bäumen und es regnet häufig. Viele Deutsche fahren im Sommer in den Urlaub, weil das Wetter dann am besten ist.`,
    textEn: `The weather in Germany is very varied. In winter it is cold and it often snows. Temperatures can drop to minus ten degrees. In spring it gets warmer and the flowers bloom. In summer it is usually warm and sunny, but there are also thunderstorms. In autumn the leaves fall from the trees and it rains frequently. Many Germans go on holiday in summer because the weather is best then.`,
    tooltips: {
      unterschiedlich: "varied, different",
      blühen: "to bloom, to blossom",
      Gewitter: "thunderstorm",
      Blätter: "leaves",
      häufig: "frequently, often",
      Urlaub: "holiday, vacation",
    },
    exercises: [
      {
        id: "ra2w-mc1",
        type: "multipleChoice",
        question: "Wie ist das Wetter im Winter?",
        options: ["Warm und sonnig", "Kalt und es schneit", "Mild und regnerisch", "Heiß und trocken"],
        correctIndex: 1,
        explanation: "'Im Winter ist es kalt und es schneit oft.'",
      },
      {
        id: "ra2w-mc2",
        type: "multipleChoice",
        question: "Wann fahren viele Deutsche in den Urlaub?",
        options: ["Im Winter", "Im Frühling", "Im Sommer", "Im Herbst"],
        correctIndex: 2,
        explanation: "'Viele Deutsche fahren im Sommer in den Urlaub.'",
      },
      {
        id: "ra2w-fb1",
        type: "fillBlank",
        prompt: "Im Herbst fallen die ___ von den Bäumen.",
        answer: "Blätter",
        explanation: "'Im Herbst fallen die Blätter von den Bäumen.'",
      },
      {
        id: "ra2w-fb2",
        type: "fillBlank",
        prompt: "Im Sommer gibt es manchmal ___.",
        answer: "Gewitter",
        alternatives: ["Gewitter."],
        explanation: "'es gibt auch Gewitter'",
      },
    ],
  },

  // ── B1 ──────────────────────────────────────────────────────────────
  {
    id: "reading-b1-work",
    title: "Arbeiten in Deutschland",
    level: "B1",
    topic: "Work",
    text: `In Deutschland arbeiten die meisten Menschen Vollzeit, also etwa vierzig Stunden pro Woche. Viele Arbeitnehmer genießen jedoch auch flexible Arbeitszeiten, das sogenannte Gleitzeitmodell. Dabei können sie selbst entscheiden, wann sie anfangen und aufhören zu arbeiten, solange sie die vereinbarte Stundenzahl erfüllen. Homeoffice ist nach der Pandemie weit verbreitet und viele Unternehmen erlauben es, mehrmals pro Woche von zu Hause aus zu arbeiten. Der gesetzliche Mindestlohn in Deutschland liegt bei über zwölf Euro pro Stunde. Urlaub haben Arbeitnehmer in der Regel mindestens zwanzig Tage im Jahr.`,
    textEn: `In Germany most people work full-time, that is about forty hours per week. Many employees also enjoy flexible working hours, the so-called flexitime model. This allows them to decide themselves when they start and finish work, as long as they fulfil the agreed number of hours. Working from home has become widespread since the pandemic and many companies allow employees to work from home several times a week. The statutory minimum wage in Germany is over twelve euros per hour. Employees are generally entitled to at least twenty days of holiday per year.`,
    tooltips: {
      Vollzeit: "full-time",
      Arbeitnehmer: "employee",
      Gleitzeitmodell: "flexitime model",
      vereinbarte: "agreed",
      Mindestlohn: "minimum wage",
      gesetzlich: "statutory, by law",
      Homeoffice: "working from home",
    },
    exercises: [
      {
        id: "rb1w-mc1",
        type: "multipleChoice",
        question: "Wie viele Stunden pro Woche arbeiten die meisten Deutschen?",
        options: ["Dreißig", "Fünfunddreißig", "Vierzig", "Fünfundvierzig"],
        correctIndex: 2,
        explanation: "'etwa vierzig Stunden pro Woche'",
      },
      {
        id: "rb1w-mc2",
        type: "multipleChoice",
        question: "Was bedeutet das Gleitzeitmodell?",
        options: [
          "Man muss immer um neun Uhr anfangen",
          "Man kann die Arbeitszeiten selbst bestimmen",
          "Man arbeitet nur vier Tage pro Woche",
          "Man bekommt mehr Gehalt",
        ],
        correctIndex: 1,
        explanation: "'können sie selbst entscheiden, wann sie anfangen und aufhören'",
      },
      {
        id: "rb1w-fb1",
        type: "fillBlank",
        prompt: "Der gesetzliche ___ in Deutschland liegt bei über zwölf Euro pro Stunde.",
        answer: "Mindestlohn",
        explanation: "Das Wort 'Mindestlohn' bedeutet minimum wage.",
      },
      {
        id: "rb1w-fb2",
        type: "fillBlank",
        prompt: "Arbeitnehmer haben mindestens ___ Urlaubstage im Jahr.",
        answer: "zwanzig",
        alternatives: ["20"],
        explanation: "'mindestens zwanzig Tage im Jahr'",
      },
    ],
  },
  {
    id: "reading-b1-environment",
    title: "Umweltschutz in Deutschland",
    level: "B1",
    topic: "Environment",
    text: `Deutschland gilt als eines der umweltbewusstesten Länder der Welt. Die Mülltrennung ist hier besonders wichtig: Papier, Glas, Plastik und Bioabfälle werden getrennt gesammelt. Das Pfandsystem für Flaschen und Dosen motiviert die Menschen, Verpackungen zurückzugeben. Erneuerbare Energien wie Wind- und Solarenergie gewinnen zunehmend an Bedeutung. Die Bundesregierung hat sich verpflichtet, bis 2045 klimaneutral zu werden. Trotzdem gibt es noch viele Herausforderungen, zum Beispiel im Bereich des Autoverkehrs und der Industrie.`,
    textEn: `Germany is considered one of the most environmentally conscious countries in the world. Waste separation is particularly important here: paper, glass, plastic and organic waste are collected separately. The deposit system for bottles and cans motivates people to return packaging. Renewable energies such as wind and solar power are gaining increasing importance. The federal government has committed to becoming climate-neutral by 2045. Nevertheless, there are still many challenges, for example in road transport and industry.`,
    tooltips: {
      umweltbewusst: "environmentally conscious",
      Mülltrennung: "waste separation, recycling",
      Bioabfall: "organic waste",
      Pfandsystem: "deposit return system",
      erneuerbare: "renewable",
      klimaneutral: "climate neutral",
      Herausforderungen: "challenges",
    },
    exercises: [
      {
        id: "rb1e-mc1",
        type: "multipleChoice",
        question: "Wofür ist Deutschland international bekannt?",
        options: [
          "Für seine Strände",
          "Für sein Umweltbewusstsein",
          "Für seine hohe Geburtenrate",
          "Für sein warmes Klima",
        ],
        correctIndex: 1,
        explanation: "'Deutschland gilt als eines der umweltbewusstesten Länder der Welt.'",
      },
      {
        id: "rb1e-mc2",
        type: "multipleChoice",
        question: "Bis wann will Deutschland klimaneutral werden?",
        options: ["2030", "2035", "2040", "2045"],
        correctIndex: 3,
        explanation: "'bis 2045 klimaneutral zu werden'",
      },
      {
        id: "rb1e-fb1",
        type: "fillBlank",
        prompt: "Das ___ für Flaschen motiviert Menschen, Verpackungen zurückzugeben.",
        answer: "Pfandsystem",
        explanation: "Das Pfandsystem ist das deposit return system.",
      },
      {
        id: "rb1e-fb2",
        type: "fillBlank",
        prompt: "Papier, Glas und Plastik werden durch ___ getrennt gesammelt.",
        answer: "Mülltrennung",
        explanation: "Mülltrennung = waste separation.",
      },
    ],
  },

  // ── B2 ──────────────────────────────────────────────────────────────
  {
    id: "reading-b2-democracy",
    title: "Die deutsche Demokratie",
    level: "B2",
    topic: "Politics",
    text: `Die Bundesrepublik Deutschland ist eine parlamentarische Demokratie, in der das Volk alle vier Jahre den Bundestag wählt. Der Bundestag ist das wichtigste Gesetzgebungsorgan des Landes. Die Regierung wird vom Bundeskanzler oder der Bundeskanzlerin geleitet, der oder die vom Bundestag gewählt wird. Das Grundgesetz, verabschiedet im Jahr 1949, bildet die rechtliche Grundlage des Staates und garantiert fundamentale Grundrechte wie Meinungsfreiheit, Versammlungsfreiheit und das Recht auf körperliche Unversehrtheit. Deutschland ist außerdem ein Föderalstaat, bestehend aus sechzehn Bundesländern, die in manchen Bereichen eigene Gesetze erlassen können.`,
    textEn: `The Federal Republic of Germany is a parliamentary democracy in which the people elect the Bundestag every four years. The Bundestag is the country's most important legislative body. The government is led by the Federal Chancellor, who is elected by the Bundestag. The Basic Law, passed in 1949, forms the legal foundation of the state and guarantees fundamental rights such as freedom of expression, freedom of assembly and the right to physical integrity. Germany is also a federal state consisting of sixteen federal states, which can enact their own laws in certain areas.`,
    tooltips: {
      parlamentarisch: "parliamentary",
      Gesetzgebungsorgan: "legislative body",
      Bundeskanzler: "Federal Chancellor",
      Grundgesetz: "Basic Law (German constitution)",
      Meinungsfreiheit: "freedom of expression",
      Versammlungsfreiheit: "freedom of assembly",
      Föderalstaat: "federal state",
      Bundesländer: "federal states",
    },
    exercises: [
      {
        id: "rb2d-mc1",
        type: "multipleChoice",
        question: "Wie oft wählen die Deutschen den Bundestag?",
        options: ["Alle zwei Jahre", "Alle drei Jahre", "Alle vier Jahre", "Alle fünf Jahre"],
        correctIndex: 2,
        explanation: "'alle vier Jahre den Bundestag wählt'",
      },
      {
        id: "rb2d-mc2",
        type: "multipleChoice",
        question: "Was ist das Grundgesetz?",
        options: [
          "Ein internationaler Vertrag",
          "Die deutsche Verfassung",
          "Ein Bundeslandgesetz",
          "Eine EU-Richtlinie",
        ],
        correctIndex: 1,
        explanation: "Das Grundgesetz 'bildet die rechtliche Grundlage des Staates'.",
      },
      {
        id: "rb2d-fb1",
        type: "fillBlank",
        prompt: "Deutschland besteht aus sechzehn ___.",
        answer: "Bundesländern",
        alternatives: ["Bundesländer"],
        explanation: "'bestehend aus sechzehn Bundesländern'",
      },
      {
        id: "rb2d-fb2",
        type: "fillBlank",
        prompt: "Das Grundgesetz wurde im Jahr ___ verabschiedet.",
        answer: "1949",
        explanation: "'verabschiedet im Jahr 1949'",
      },
    ],
  },
  {
    id: "reading-b2-economy",
    title: "Die deutsche Wirtschaft",
    level: "B2",
    topic: "Economy",
    text: `Deutschland ist die größte Volkswirtschaft Europas und eine der bedeutendsten der Welt. Die Stärke der deutschen Wirtschaft beruht auf einem breit aufgestellten Mittelstand sowie auf international wettbewerbsfähigen Großunternehmen, insbesondere in der Automobil-, Chemie- und Maschinenbaubranche. Exportorientierung spielt eine zentrale Rolle: Deutschland zählt zu den größten Exporteuren weltweit. Gleichzeitig steht die Wirtschaft vor erheblichen Herausforderungen, darunter der demografische Wandel, der Fachkräftemangel und die Transformation hin zu einer klimaneutralen Industrie. Digitalisierung und Innovation gelten als Schlüssel für die Wettbewerbsfähigkeit der Zukunft.`,
    textEn: `Germany has the largest economy in Europe and one of the most significant in the world. The strength of the German economy is based on a broadly positioned SME sector as well as internationally competitive large companies, particularly in the automotive, chemical and mechanical engineering sectors. Export orientation plays a central role: Germany is one of the world's largest exporters. At the same time, the economy faces considerable challenges, including demographic change, a shortage of skilled workers, and the transition to a climate-neutral industry. Digitalisation and innovation are considered key to future competitiveness.`,
    tooltips: {
      Volkswirtschaft: "national economy",
      Mittelstand: "SMEs, medium-sized businesses",
      wettbewerbsfähig: "competitive",
      Fachkräftemangel: "shortage of skilled workers",
      demografischer: "demographic",
      Digitalisierung: "digitalisation",
      Transformation: "transformation, transition",
    },
    exercises: [
      {
        id: "rb2e-mc1",
        type: "multipleChoice",
        question: "Welche Branchen sind besonders wichtig für Deutschland?",
        options: [
          "Tourismus und Mode",
          "Automobil, Chemie und Maschinenbau",
          "Landwirtschaft und Fischerei",
          "Banken und Versicherungen",
        ],
        correctIndex: 1,
        explanation: "'insbesondere in der Automobil-, Chemie- und Maschinenbaubranche'",
      },
      {
        id: "rb2e-mc2",
        type: "multipleChoice",
        question: "Was ist eine Herausforderung für die deutsche Wirtschaft?",
        options: [
          "Zu viele Fachkräfte",
          "Zu wenig Export",
          "Fachkräftemangel",
          "Zu viel Digitalisierung",
        ],
        correctIndex: 2,
        explanation: "'der Fachkräftemangel' wird als Herausforderung genannt.",
      },
      {
        id: "rb2e-fb1",
        type: "fillBlank",
        prompt: "Deutschland zählt zu den größten ___ weltweit.",
        answer: "Exporteuren",
        explanation: "'Deutschland zählt zu den größten Exporteuren weltweit.'",
      },
      {
        id: "rb2e-fb2",
        type: "fillBlank",
        prompt: "___ und Innovation gelten als Schlüssel für die Zukunft.",
        answer: "Digitalisierung",
        explanation: "'Digitalisierung und Innovation gelten als Schlüssel'",
      },
    ],
  },

  // ── C1 ──────────────────────────────────────────────────────────────
  {
    id: "reading-c1-academic",
    title: "Akademisches Schreiben auf Deutsch",
    level: "C1",
    topic: "Academic language",
    text: `Akademisches Schreiben auf Deutsch zeichnet sich durch Präzision, logische Argumentation und einen formellen Stil aus. Anders als in der Alltagssprache werden Passivkonstruktionen und nominale Ausdrucksweisen bevorzugt, um Sachverhalte objektiv darzustellen. Wissenschaftliche Texte verlangen eine klare Gliederung: Einleitung, Hauptteil und Schluss. In der Einleitung wird die Forschungsfrage formuliert und in den wissenschaftlichen Kontext eingebettet. Der Hauptteil präsentiert und diskutiert die Befunde unter Rückgriff auf Fachliteratur. Der Schluss fasst die Ergebnisse zusammen und zeigt Implikationen oder offene Fragen auf. Plagiate gelten als schwerer akademischer Verstoß und werden mit Sanktionen geahndet.`,
    textEn: `Academic writing in German is characterised by precision, logical argumentation and a formal style. Unlike everyday language, passive constructions and nominal expressions are preferred in order to present facts objectively. Academic texts require a clear structure: introduction, main body and conclusion. The introduction formulates the research question and embeds it in the academic context. The main body presents and discusses the findings with reference to specialist literature. The conclusion summarises the results and highlights implications or open questions. Plagiarism is considered a serious academic offence and is punished with sanctions.`,
    tooltips: {
      Präzision: "precision",
      Passivkonstruktionen: "passive constructions",
      nominale: "nominal (noun-based)",
      Gliederung: "structure, outline",
      Befunde: "findings",
      Fachliteratur: "specialist / academic literature",
      Plagiat: "plagiarism",
      geahndet: "punished, sanctioned",
    },
    exercises: [
      {
        id: "rc1a-mc1",
        type: "multipleChoice",
        question: "Was kennzeichnet akademisches Schreiben auf Deutsch?",
        options: [
          "Umgangssprache und kurze Sätze",
          "Präzision und formeller Stil",
          "Viele Adjektive und Bilder",
          "Persönliche Meinungen ohne Belege",
        ],
        correctIndex: 1,
        explanation: "'zeichnet sich durch Präzision … und einen formellen Stil aus'",
      },
      {
        id: "rc1a-mc2",
        type: "multipleChoice",
        question: "Was enthält die Einleitung eines akademischen Textes?",
        options: [
          "Die Schlussfolgerungen",
          "Die Ergebnisse der Studie",
          "Die Forschungsfrage und den wissenschaftlichen Kontext",
          "Die vollständige Literaturliste",
        ],
        correctIndex: 2,
        explanation: "'In der Einleitung wird die Forschungsfrage formuliert und … eingebettet.'",
      },
      {
        id: "rc1a-fb1",
        type: "fillBlank",
        prompt: "Im akademischen Schreiben werden ___ bevorzugt, um Sachverhalte objektiv darzustellen.",
        answer: "Passivkonstruktionen",
        alternatives: ["Passivkonstruktionen und nominale Ausdrucksweisen"],
        explanation: "'Passivkonstruktionen und nominale Ausdrucksweisen bevorzugt'",
      },
      {
        id: "rc1a-fb2",
        type: "fillBlank",
        prompt: "___ gelten als schwerer akademischer Verstoß.",
        answer: "Plagiate",
        explanation: "'Plagiate gelten als schwerer akademischer Verstoß'",
      },
    ],
  },
  {
    id: "reading-c1-idioms",
    title: "Deutsche Redewendungen",
    level: "C1",
    topic: "Idioms",
    text: `Die deutsche Sprache ist reich an Redewendungen, die oft wörtlich übersetzt keinen Sinn ergeben, aber idiomatisch eine präzise Bedeutung haben. Wer „Tomaten auf den Augen haben" sagt, meint damit, dass jemand etwas Offensichtliches nicht sieht. „Jemandem auf den Zahn fühlen" bedeutet, jemanden genau zu befragen oder zu prüfen. „Das ist nicht mein Bier" drückt aus, dass etwas einen nicht betrifft oder interessiert. Viele dieser Redewendungen haben ihren Ursprung in handwerklichen Berufen, in der Landwirtschaft oder in historischen Ereignissen. Das Beherrschen von Idiomen gilt als Zeichen fortgeschrittener Sprachkompetenz.`,
    textEn: `The German language is rich in idioms that often make no sense translated literally but have a precise idiomatic meaning. Saying "Tomaten auf den Augen haben" (literally: to have tomatoes on your eyes) means that someone cannot see something obvious. "Jemandem auf den Zahn fühlen" (to feel someone's tooth) means to question or examine someone closely. "Das ist nicht mein Bier" (that is not my beer) expresses that something does not concern or interest you. Many of these idioms have their origins in craft trades, agriculture or historical events. Mastering idioms is considered a sign of advanced language proficiency.`,
    tooltips: {
      Redewendungen: "idioms, set expressions",
      wörtlich: "literally",
      idiomatisch: "idiomatic",
      offensichtlich: "obvious",
      Ursprung: "origin",
      Sprachkompetenz: "language proficiency",
      handwerklich: "relating to craft/trade",
    },
    exercises: [
      {
        id: "rc1i-mc1",
        type: "multipleChoice",
        question: `Was bedeutet \u201ETomaten auf den Augen haben\u201C?`,
        options: [
          "Man sieht sehr gut",
          "Man ist sehr müde",
          "Man übersieht etwas Offensichtliches",
          "Man mag kein Gemüse",
        ],
        correctIndex: 2,
        explanation: "'meint damit, dass jemand etwas Offensichtliches nicht sieht'",
      },
      {
        id: "rc1i-mc2",
        type: "multipleChoice",
        question: `Was drückt \u201EDas ist nicht mein Bier\u201C aus?`,
        options: [
          "Man trinkt kein Bier",
          "Etwas geht einen nichts an",
          "Man ist sehr beschäftigt",
          "Etwas schmeckt nicht",
        ],
        correctIndex: 1,
        explanation: "'dass etwas einen nicht betrifft oder interessiert'",
      },
      {
        id: "rc1i-fb1",
        type: "fillBlank",
        prompt: "Viele Redewendungen haben ihren ___ in handwerklichen Berufen.",
        answer: "Ursprung",
        explanation: "'haben ihren Ursprung in handwerklichen Berufen'",
      },
      {
        id: "rc1i-fb2",
        type: "fillBlank",
        prompt: "'Jemandem auf den Zahn fühlen' bedeutet, jemanden genau zu ___ oder zu prüfen.",
        answer: "befragen",
        explanation: "'jemanden genau zu befragen oder zu prüfen'",
      },
    ],
  },

  // ── C2 ──────────────────────────────────────────────────────────────
  {
    id: "reading-c2-nuance",
    title: "Sprachliche Nuancen im Deutschen",
    level: "C2",
    topic: "Nuanced language",
    text: `Das Deutsche zeichnet sich durch eine Vielzahl lexikalischer und grammatischer Mittel aus, die feine semantische Unterschiede ausdrücken. Die Modalpartikeln – Wörter wie „doch", „ja", „eigentlich" und „halt" – sind ein besonders markantes Beispiel: Sie modifizieren den Ton einer Aussage und signalisieren Einstellungen wie Überraschung, Resignation oder Selbstverständlichkeit, ohne dass dies explizit formuliert werden müsste. Darüber hinaus ermöglicht die Kompositionsfreiheit des Deutschen die Bildung komplexer Komposita, die in anderen Sprachen eine ganze Phrase erfordern würden. Dieses Zusammenspiel von Präzision und Verdichtung macht die Sprache für literarische und wissenschaftliche Zwecke besonders geeignet.`,
    textEn: `German is characterised by a variety of lexical and grammatical means that express subtle semantic differences. Modal particles – words like "doch", "ja", "eigentlich" and "halt" – are a particularly striking example: they modify the tone of an utterance and signal attitudes such as surprise, resignation or self-evidence without these having to be explicitly stated. Furthermore, the freedom of composition in German enables the formation of complex compound words that would require a whole phrase in other languages. This interplay of precision and density makes the language particularly suitable for literary and academic purposes.`,
    tooltips: {
      lexikalisch: "lexical",
      semantisch: "semantic",
      Modalpartikeln: "modal particles",
      signalisieren: "to signal, to indicate",
      Kompositionsfreiheit: "freedom to form compound words",
      Komposita: "compound words",
      Verdichtung: "density, compression",
    },
    exercises: [
      {
        id: "rc2n-mc1",
        type: "multipleChoice",
        question: "Was sind Modalpartikeln?",
        options: [
          "Wörter, die den Ton einer Aussage modifizieren",
          "Trennbare Verben",
          "Substantive mit Artikel",
          "Konjunktionen in Nebensätzen",
        ],
        correctIndex: 0,
        explanation: "'Sie modifizieren den Ton einer Aussage und signalisieren Einstellungen'",
      },
      {
        id: "rc2n-mc2",
        type: "multipleChoice",
        question: "Wofür ist das Deutsche besonders geeignet?",
        options: [
          "Für kurze Alltagsgespräche",
          "Für literarische und wissenschaftliche Zwecke",
          "Für informelle Kommunikation",
          "Für Werbetexte",
        ],
        correctIndex: 1,
        explanation: "'macht die Sprache für literarische und wissenschaftliche Zwecke besonders geeignet'",
      },
      {
        id: "rc2n-fb1",
        type: "fillBlank",
        prompt: "Deutsche ___ können in anderen Sprachen eine ganze Phrase erfordern.",
        answer: "Komposita",
        explanation: "Komposita sind compound words — eine Stärke des Deutschen.",
      },
      {
        id: "rc2n-fb2",
        type: "fillBlank",
        prompt: "Modalpartikeln signalisieren Einstellungen, ohne dass dies ___ formuliert werden müsste.",
        answer: "explizit",
        explanation: "'ohne dass dies explizit formuliert werden müsste'",
      },
    ],
  },
  {
    id: "reading-c2-register",
    title: "Sprachliche Register im Deutschen",
    level: "C2",
    topic: "Language register",
    text: `Die Beherrschung verschiedener Sprachregister ist für fortgeschrittene Deutschlernende unerlässlich. Das formelle Register – verwendet in behördlichen Schreiben, akademischen Texten und Geschäftskorrespondenz – zeichnet sich durch vollständige Satzstrukturen, unpersönliche Formulierungen und einen elaborierten Wortschatz aus. Das informelle Register der Alltagssprache hingegen weist verkürzte Formen, Umgangsausdrücke und eine höhere syntaktische Flexibilität auf. Zwischen diesen Polen existieren zahlreiche Zwischenstufen, darunter das sachlich-neutrale Register von Nachrichtentexten oder die bewusst eingängige Sprache der Werbung. Ein kompetenter Sprecher vermag situationsabhängig zwischen diesen Registern zu wechseln.`,
    textEn: `Mastery of various language registers is essential for advanced German learners. The formal register – used in official correspondence, academic texts and business communication – is characterised by complete sentence structures, impersonal formulations and an elaborate vocabulary. The informal register of everyday speech, on the other hand, features abbreviated forms, colloquial expressions and greater syntactic flexibility. Between these poles there are numerous intermediate levels, including the factual-neutral register of news texts or the deliberately catchy language of advertising. A competent speaker is able to switch between these registers depending on the situation.`,
    tooltips: {
      Register: "register (linguistic level)",
      unerlässlich: "essential, indispensable",
      behördlich: "official, governmental",
      elaboriert: "elaborate, sophisticated",
      syntaktisch: "syntactic",
      situationsabhängig: "depending on the situation",
      kompetent: "competent, proficient",
    },
    exercises: [
      {
        id: "rc2r-mc1",
        type: "multipleChoice",
        question: "Was kennzeichnet das formelle Register?",
        options: [
          "Umgangsausdrücke und Abkürzungen",
          "Vollständige Satzstrukturen und elaborierter Wortschatz",
          "Syntaktische Flexibilität",
          "Kurze informelle Phrasen",
        ],
        correctIndex: 1,
        explanation: "'vollständige Satzstrukturen, unpersönliche Formulierungen und einen elaborierten Wortschatz'",
      },
      {
        id: "rc2r-mc2",
        type: "multipleChoice",
        question: "Was ist ein Merkmal des informellen Registers?",
        options: [
          "Unpersönliche Formulierungen",
          "Akademischer Wortschatz",
          "Umgangsausdrücke",
          "Behördliche Strukturen",
        ],
        correctIndex: 2,
        explanation: "'Umgangsausdrücke und eine höhere syntaktische Flexibilität'",
      },
      {
        id: "rc2r-fb1",
        type: "fillBlank",
        prompt: "Ein kompetenter Sprecher wechselt ___ zwischen verschiedenen Registern.",
        answer: "situationsabhängig",
        explanation: "'vermag situationsabhängig zwischen diesen Registern zu wechseln'",
      },
      {
        id: "rc2r-fb2",
        type: "fillBlank",
        prompt: "Die Beherrschung verschiedener Register ist für fortgeschrittene Lernende ___.",
        answer: "unerlässlich",
        explanation: "'ist für fortgeschrittene Deutschlernende unerlässlich'",
      },
    ],
  },
];
